$script_provision = <<-SCRIPT
  echo "Provisioning NGINX"
  apt-get -qq update && apt-get -qq install -y nginx
  echo "Provisioning MYSQL"
  apt-get -qq install -y mysql-server-5.7
  echo "Configuring remote access"
  cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf
  echo "Restarting MYSQL"
  service mysql restart
SCRIPT

$script_create_user = <<-SCRIPT
  echo Creating user on mysql
  mysql -e "CREATE USER 'softcube'@'%' IDENTIFIED BY 'Brasil@77!';"
  mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'softcube'@'%';"
  mysql -e "FLUSH PRIVILEGES;"
  echo User created
SCRIPT

$script_create_database = <<-SCRIPT
  echo Creating database 'store'
  mysql -e "CREATE DATABASE store;"
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.network "forwarded_port", guest: 80, host: 8090
  config.vm.network "forwarded_port", guest: #guest_port#, host: #host_port#
  config.vm.network "public_network", ip: "#guest_address#"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "./configs", "/configs"

  config.vm.provision "shell", inline: "cat /configs/#public_key#.pub >> .ssh/authorized_keys"

  config.vm.provision "shell", inline: $script_provision
  config.vm.provision "shell", inline: $script_create_user
  config.vm.provision "shell", inline: $script_create_database
end
